apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:f95e4f1454deca015390b9dcdd875d58fa36a9ef4228f1794bc6cdb9376cf1ad
  name: quay.io/bluesman/vote-api
  newName: quay.io/bluesman/vote-api
- digest: sha256:703b3517b36784b5ae66e9aa2401353a177ca4b50af8871d49a29b20a544a515
  name: quay.io/bluesman/vote-ui
  newName: quay.io/bluesman/vote-ui
