apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:f95e4f1454deca015390b9dcdd875d58fa36a9ef4228f1794bc6cdb9376cf1ad
  name: quay.io/bluesman/vote-api
  newName: quay.io/bluesman/vote-api
- digest: sha256:4e53664362b41c1ae497954898d568b659b4236dd2fab8486d8ddaf19ac08825
  name: quay.io/bluesman/vote-ui
  newName: quay.io/bluesman/vote-ui
- digest: sha256:a586db37e46c3944c91cd871f1bc01c031aa6e8925c619db0a5190e4cf717f0c
  name: quay.io/btenneti/vote-api
  newName: quay.io/btenneti/vote-api
- digest: sha256:3091cbe5f608a752ed421b530b8f9c7ea8f5fe07e6cd17d4ffe009f89efe3b93
  name: quay.io/btenneti/vote-ui
  newName: quay.io/btenneti/vote-ui
